# Headers and Sources
#
pub_hdrs = src/h{luaconf lua lualib lauxlib}
lib{lua}: src/h{*} src/c{* -lua -luac} src/hxx{lua}

# Build and Export Options
#
ipath = [dir_path] $src_base/src
cc.poptions =+ "-I$ipath"
lib{lua}: cc.export.poptions = "-I$ipath"
#
poptions = -DLUA_COMPAT_5_3
#
switch ($cc.target.class)
{
  case 'windows'
  {
    # `luaconf.h` automatically deduces Windows as target platform. Thus,
    # appending the following preprocessor directive leads to `macro redefine`
    # warnings/errors and is omitted. The scope is important to not fall
    # through to the next case block.
    #
    # poptions += -DLUA_USE_WINDOWS
  }
  case 'linux'
    poptions += -DLUA_USE_LINUX
  case 'macos'
    poptions += -DLUA_USE_MACOSX
  default
    poptions += -DLUA_USE_POSIX -DLUA_USE_DLOPEN
}
#
cc.poptions += $poptions
lib{lua}: cc.export.poptions += $poptions
#
if ($cc.target.class == 'windows')
{
  objs{*}: cc.poptions += -DLUA_BUILD_AS_DLL
  libs{lua}: cc.export.poptions += -DLUA_BUILD_AS_DLL
}
else
  cc.libs += -lm -ldl

# Versioning
#
if $version.pre_release
  lib{lua}: bin.lib.version = "-$version.project_id"
else
  lib{lua}: bin.lib.version = "-$version.major.$version.minor"

# Installation
#
h{*}: install = false
for hdr : $pub_hdrs
  $hdr@src/: install = include/
hxx{*}: install = include/

