# Use an immediate import of `liblua%lib{lua}` to be able
# to export it for backwards compatibility as `lua%lib{lua}`.
# For installation, it must be stated
# as a prerequisite to this directory.
#
# See: https://github.com/build2/build2/issues/331
#
import! [rule_hint=c.link] liblua = liblua%lib{lua}
./: $liblua

import static_lua = liblua%liba{lua}
import shared_lua = liblua%libs{lua}

./: exe{luac}: c{luac} $static_lua
./: exe{lua}: c{lua} $shared_lua
