# Use an immediate import of `liblua%lib{lua}` to be able
# to export it for backwards compatibility as `lua%lib{lua}`.
# For installation, it must be stated
# as a prerequisite to this directory.
#
# See: https://github.com/build2/build2/issues/331
#
import! [rule_hint=c.link] liblua = liblua%lib{lua}
# ./: $liblua

# Lua Compiler
#
import luac_libs = liblua%liba{lua}
./: exe{luac}: c{luac} $luac_libs

# Lua Interpreter
#
import lua_libs = liblua%libs{lua}

if $config.lua.readline
{
  import lua_libs += readline%lib{readline}
  obj{lua}: c.poptions += -DLUA_USE_READLINE
}

./: exe{lua}: c{lua} $lua_libs
