# Use deprecated import of `lib{lua}` from `lua` package.
#
# Also, nominate the rule that should be used to
# search for the library in the installed case.
# For C/C++ libraries the two rule options are `c.link` and `cxx.link`
# and we should pick the same as what is used to link the user project.
#
# See: https://github.com/build2/HOWTO/blob/master/entries/convey-additional-information-with-exe-lib.md
#
import! [rule_hint=c.link] liblua = lua%lib{lua}

scripts_dir = [dir_path] ../../scripts/
include $scripts_dir
scripts = $scripts_dir/{$($scripts_dir/ scripts)}

exe{interpreter}: c{interpreter} $liblua testscript
