# Use deprecated import of `lib{lua}` from `lua` package.
#
import! [rule_hint=c.link] liblua = lua%lib{lua}

scripts_dir = [dir_path] ../../scripts/
include $scripts_dir
scripts = $scripts_dir/{$($scripts_dir/ scripts)}

exe{interpreter}: c{interpreter} $liblua testscript
