import! [metadata] lua = liblua%lib{lua}
cxx_compiled = [bool] $($lua: liblua.compiled_as_cxx)

exe{tests}: cxx{*} $lua file{test.lua}
{
  test.arguments = $src_base/test.lua
}

if $cxx_compiled
  cxx.poptions += -DLUA_COMPILED_AS_CXX
