# Use deprecated import of `lib{lua}` from `lua` package.
#
import liblua = lua%lib{lua}

scripts_dir = [dir_path] ../../scripts/
include $scripts_dir
scripts = $scripts_dir/{$($scripts_dir/ scripts)}

exe{interpreter}: cxx{interpreter} $liblua testscript
